---

- name: ensure letsencrypt acme-challenge path
  file:
    path: "{{ ssl_webroot_path }}"
    state: "directory"
    mode: 0755
  become: true

- name: unlink app nginx config
  file:
    path: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
    state: "absent"
  become: true

- name: create temporary nginx config
  template:
    src: "../templates/nginx_tmp_site.conf"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
  become: true

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted

- name: create (or renew) letsencrypt ssl cert
  command: "{{ letsencrypt_command }}"
  become: true

- name: setup a cron to renew the SSL cert every day
  cron:
    name: "renew letsencrypt cert"
    minute: "23"
    hour: "6,18"
    job: "letsencrypt renew --email {{ ssl_support_email }} --agree-tos"
  become: true

- name: unlink tmp nginx config
  file:
    path: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
    state: "absent"
  become: true
