---

- name: ensure /etc/default/ dir exists
  become: true
  file:
    path: /etc/default
    state: directory

- name: install the systemd unit file for shaman 
  template:
    src: systemd/shaman.service.j2
    dest: /etc/systemd/system/shaman.service
  become: true
  notify:
     - reload systemd

- name: ensure shaman is enabled and running
  become: true
  service:
    name: shaman
    state: started
    enabled: yes
